# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from apivideo.paths.upload_tokens_upload_token.delete import DEleteUploadTokensUploadToken
from apivideo.paths.upload_tokens.get import GEtUploadTokens
from apivideo.paths.upload_tokens_upload_token.get import GEtUploadTokensUploadToken
from apivideo.paths.upload.post import POstUpload
from apivideo.paths.upload_tokens.post import POstUploadTokens


class VideosDelegatedUploadApi(
    DEleteUploadTokensUploadToken,
    GEtUploadTokens,
    GEtUploadTokensUploadToken,
    POstUpload,
    POstUploadTokens,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
