# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from video-api.paths.players_player_id.delete import DEletePlayersPlayerId
from video-api.paths.players_player_id_logo.delete import DEletePlayersPlayerIdLogo
from video-api.paths.players.get import GEtPlayers
from video-api.paths.players_player_id.get import GEtPlayersPlayerId
from video-api.paths.players_player_id.patch import PAtchPlayersPlayerId
from video-api.paths.players.post import POstPlayers
from video-api.paths.players_player_id_logo.post import POstPlayersPlayerIdLogo


class PlayersApi(
    DEletePlayersPlayerId,
    DEletePlayersPlayerIdLogo,
    GEtPlayers,
    GEtPlayersPlayerId,
    PAtchPlayersPlayerId,
    POstPlayers,
    POstPlayersPlayerIdLogo,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
