/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.outmatchapi.api


import com.squareup.moshi.Json

/**
 * 
 *
 * @param firstName 
 * @param lastName 
 * @param company 
 */


data class UpdateUserRequest (

    @Json(name = "firstName")
    val firstName: kotlin.String,

    @Json(name = "lastName")
    val lastName: kotlin.String,

    @Json(name = "company")
    val company: kotlin.String

)

