/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outmatchapi.slack;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import invalidPackageName.JSON;

/**
 * ChatScheduledMessagesListSchemaScheduledMessagesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-08T22:09:03.829372Z[Etc/UTC]")
public class ChatScheduledMessagesListSchemaScheduledMessagesInner {
  public static final String SERIALIZED_NAME_CHANNEL_ID = "channel_id";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  private String channelId;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  private Integer dateCreated;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_POST_AT = "post_at";
  @SerializedName(SERIALIZED_NAME_POST_AT)
  private Integer postAt;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public ChatScheduledMessagesListSchemaScheduledMessagesInner() {
  }

  public ChatScheduledMessagesListSchemaScheduledMessagesInner channelId(String channelId) {
    
    this.channelId = channelId;
    return this;
  }

   /**
   * Get channelId
   * @return channelId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getChannelId() {
    return channelId;
  }


  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }


  public ChatScheduledMessagesListSchemaScheduledMessagesInner dateCreated(Integer dateCreated) {
    
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getDateCreated() {
    return dateCreated;
  }


  public void setDateCreated(Integer dateCreated) {
    this.dateCreated = dateCreated;
  }


  public ChatScheduledMessagesListSchemaScheduledMessagesInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ChatScheduledMessagesListSchemaScheduledMessagesInner postAt(Integer postAt) {
    
    this.postAt = postAt;
    return this;
  }

   /**
   * Get postAt
   * @return postAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getPostAt() {
    return postAt;
  }


  public void setPostAt(Integer postAt) {
    this.postAt = postAt;
  }


  public ChatScheduledMessagesListSchemaScheduledMessagesInner text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatScheduledMessagesListSchemaScheduledMessagesInner chatScheduledMessagesListSchemaScheduledMessagesInner = (ChatScheduledMessagesListSchemaScheduledMessagesInner) o;
    return Objects.equals(this.channelId, chatScheduledMessagesListSchemaScheduledMessagesInner.channelId) &&
        Objects.equals(this.dateCreated, chatScheduledMessagesListSchemaScheduledMessagesInner.dateCreated) &&
        Objects.equals(this.id, chatScheduledMessagesListSchemaScheduledMessagesInner.id) &&
        Objects.equals(this.postAt, chatScheduledMessagesListSchemaScheduledMessagesInner.postAt) &&
        Objects.equals(this.text, chatScheduledMessagesListSchemaScheduledMessagesInner.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, dateCreated, id, postAt, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatScheduledMessagesListSchemaScheduledMessagesInner {\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("channel_id");
    openapiFields.add("date_created");
    openapiFields.add("id");
    openapiFields.add("post_at");
    openapiFields.add("text");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("channel_id");
    openapiRequiredFields.add("date_created");
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("post_at");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ChatScheduledMessagesListSchemaScheduledMessagesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ChatScheduledMessagesListSchemaScheduledMessagesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChatScheduledMessagesListSchemaScheduledMessagesInner is not found in the empty JSON string", ChatScheduledMessagesListSchemaScheduledMessagesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ChatScheduledMessagesListSchemaScheduledMessagesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChatScheduledMessagesListSchemaScheduledMessagesInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChatScheduledMessagesListSchemaScheduledMessagesInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("channel_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channel_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channel_id").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChatScheduledMessagesListSchemaScheduledMessagesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChatScheduledMessagesListSchemaScheduledMessagesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChatScheduledMessagesListSchemaScheduledMessagesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChatScheduledMessagesListSchemaScheduledMessagesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ChatScheduledMessagesListSchemaScheduledMessagesInner>() {
           @Override
           public void write(JsonWriter out, ChatScheduledMessagesListSchemaScheduledMessagesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChatScheduledMessagesListSchemaScheduledMessagesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChatScheduledMessagesListSchemaScheduledMessagesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChatScheduledMessagesListSchemaScheduledMessagesInner
  * @throws IOException if the JSON string is invalid with respect to ChatScheduledMessagesListSchemaScheduledMessagesInner
  */
  public static ChatScheduledMessagesListSchemaScheduledMessagesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChatScheduledMessagesListSchemaScheduledMessagesInner.class);
  }

 /**
  * Convert an instance of ChatScheduledMessagesListSchemaScheduledMessagesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

