/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LiveStreamSession {
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<Box<crate::models::LiveStreamSessionClient>>,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<crate::models::LiveStreamSessionDevice>>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<crate::models::LiveStreamSessionLocation>>,
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<Box<crate::models::VideoSessionOs>>,
    #[serde(rename = "referrer", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<Box<crate::models::LiveStreamSessionReferrer>>,
    #[serde(rename = "session", skip_serializing_if = "Option::is_none")]
    pub session: Option<Box<crate::models::LiveStreamSessionSession>>,
}

impl LiveStreamSession {
    pub fn new() -> LiveStreamSession {
        LiveStreamSession {
            client: None,
            device: None,
            location: None,
            os: None,
            referrer: None,
            session: None,
        }
    }
}


