=begin
#Outmatch API

#Outmatch API

The version of the OpenAPI document: 0.0.45
Contact: internal@outmatchapi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

module api
  VERSION = '0.0.45'
end
