/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApiTestErrorSchema : Schema for error response api.test method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiTestErrorSchema {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl ApiTestErrorSchema {
    /// Schema for error response api.test method
    pub fn new(error: String, ok: crate::models::DefsOkFalse) -> ApiTestErrorSchema {
        ApiTestErrorSchema {
            error,
            ok,
        }
    }
}


