/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outmatchapi.slack;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.outmatchapi.slack.ObjsComment;
import com.outmatchapi.slack.ObjsFile;
import com.outmatchapi.slack.ObjsMessage;
import com.outmatchapi.slack.StarsListSchemaItemsInnerInnerAnyOf;
import com.outmatchapi.slack.StarsListSchemaItemsInnerInnerAnyOf1;
import com.outmatchapi.slack.StarsListSchemaItemsInnerInnerAnyOf2;
import com.outmatchapi.slack.StarsListSchemaItemsInnerInnerAnyOf3;
import com.outmatchapi.slack.StarsListSchemaItemsInnerInnerAnyOf4;
import com.outmatchapi.slack.StarsListSchemaItemsInnerInnerAnyOf5;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StarsListSchemaItemsInnerInner
 */
public class StarsListSchemaItemsInnerInnerTest {
    private final StarsListSchemaItemsInnerInner model = new StarsListSchemaItemsInnerInner();

    /**
     * Model tests for StarsListSchemaItemsInnerInner
     */
    @Test
    public void testStarsListSchemaItemsInnerInner() {
        // TODO: test StarsListSchemaItemsInnerInner
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'dateCreate'
     */
    @Test
    public void dateCreateTest() {
        // TODO: test dateCreate
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

}
