/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.outmatchapi.slack

import com.outmatchapi.slack.ConversationIMChannelObjectFromConversationsMethodsSharesInner
import com.outmatchapi.slack.ConversationObjectParentConversationInner
import com.outmatchapi.slack.ObjsChannelLatestInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param created 
 * @param id 
 * @param isIm 
 * @param isOrgShared 
 * @param priority 
 * @param user 
 * @param hasPins 
 * @param isArchived 
 * @param isExtShared 
 * @param isFrozen 
 * @param isOpen 
 * @param isShared 
 * @param isStarred 
 * @param isUserDeleted 
 * @param lastRead 
 * @param latest 
 * @param parentConversation 
 * @param pinCount 
 * @param shares 
 * @param unreadCount 
 * @param unreadCountDisplay 
 * @param version 
 */


data class ConversationIMChannelObjectFromConversationsMethods (

    @Json(name = "created")
    val created: kotlin.Int,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "is_im")
    val isIm: kotlin.Boolean,

    @Json(name = "is_org_shared")
    val isOrgShared: kotlin.Boolean,

    @Json(name = "priority")
    val priority: java.math.BigDecimal,

    @Json(name = "user")
    val user: kotlin.String,

    @Json(name = "has_pins")
    val hasPins: kotlin.Boolean? = null,

    @Json(name = "is_archived")
    val isArchived: kotlin.Boolean? = null,

    @Json(name = "is_ext_shared")
    val isExtShared: kotlin.Boolean? = null,

    @Json(name = "is_frozen")
    val isFrozen: kotlin.Boolean? = null,

    @Json(name = "is_open")
    val isOpen: kotlin.Boolean? = null,

    @Json(name = "is_shared")
    val isShared: kotlin.Boolean? = null,

    @Json(name = "is_starred")
    val isStarred: kotlin.Boolean? = null,

    @Json(name = "is_user_deleted")
    val isUserDeleted: kotlin.Boolean? = null,

    @Json(name = "last_read")
    val lastRead: kotlin.String? = null,

    @Json(name = "latest")
    val latest: kotlin.collections.List<ObjsChannelLatestInner>? = null,

    @Json(name = "parent_conversation")
    val parentConversation: kotlin.collections.List<ConversationObjectParentConversationInner>? = null,

    @Json(name = "pin_count")
    val pinCount: kotlin.Int? = null,

    @Json(name = "shares")
    val shares: kotlin.collections.Set<ConversationIMChannelObjectFromConversationsMethodsSharesInner>? = null,

    @Json(name = "unread_count")
    val unreadCount: kotlin.Int? = null,

    @Json(name = "unread_count_display")
    val unreadCountDisplay: kotlin.Int? = null,

    @Json(name = "version")
    val version: kotlin.Int? = null

)

