/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

API version: 1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slack

import (
	"encoding/json"
)

// ConversationsListSuccessSchema Schema for successful response from conversations.list method
type ConversationsListSuccessSchema struct {
	Channels [][]ObjsConversationInner `json:"channels"`
	Ok DefsOkTrue `json:"ok"`
	ResponseMetadata *AdminConversationsGetTeamsSchemaResponseMetadata `json:"response_metadata,omitempty"`
}

// NewConversationsListSuccessSchema instantiates a new ConversationsListSuccessSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConversationsListSuccessSchema(channels [][]ObjsConversationInner, ok DefsOkTrue) *ConversationsListSuccessSchema {
	this := ConversationsListSuccessSchema{}
	this.Channels = channels
	this.Ok = ok
	return &this
}

// NewConversationsListSuccessSchemaWithDefaults instantiates a new ConversationsListSuccessSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConversationsListSuccessSchemaWithDefaults() *ConversationsListSuccessSchema {
	this := ConversationsListSuccessSchema{}
	return &this
}

// GetChannels returns the Channels field value
func (o *ConversationsListSuccessSchema) GetChannels() [][]ObjsConversationInner {
	if o == nil {
		var ret [][]ObjsConversationInner
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *ConversationsListSuccessSchema) GetChannelsOk() ([][]ObjsConversationInner, bool) {
	if o == nil {
    return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *ConversationsListSuccessSchema) SetChannels(v [][]ObjsConversationInner) {
	o.Channels = v
}

// GetOk returns the Ok field value
func (o *ConversationsListSuccessSchema) GetOk() DefsOkTrue {
	if o == nil {
		var ret DefsOkTrue
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *ConversationsListSuccessSchema) GetOkOk() (*DefsOkTrue, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *ConversationsListSuccessSchema) SetOk(v DefsOkTrue) {
	o.Ok = v
}

// GetResponseMetadata returns the ResponseMetadata field value if set, zero value otherwise.
func (o *ConversationsListSuccessSchema) GetResponseMetadata() AdminConversationsGetTeamsSchemaResponseMetadata {
	if o == nil || isNil(o.ResponseMetadata) {
		var ret AdminConversationsGetTeamsSchemaResponseMetadata
		return ret
	}
	return *o.ResponseMetadata
}

// GetResponseMetadataOk returns a tuple with the ResponseMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationsListSuccessSchema) GetResponseMetadataOk() (*AdminConversationsGetTeamsSchemaResponseMetadata, bool) {
	if o == nil || isNil(o.ResponseMetadata) {
    return nil, false
	}
	return o.ResponseMetadata, true
}

// HasResponseMetadata returns a boolean if a field has been set.
func (o *ConversationsListSuccessSchema) HasResponseMetadata() bool {
	if o != nil && !isNil(o.ResponseMetadata) {
		return true
	}

	return false
}

// SetResponseMetadata gets a reference to the given AdminConversationsGetTeamsSchemaResponseMetadata and assigns it to the ResponseMetadata field.
func (o *ConversationsListSuccessSchema) SetResponseMetadata(v AdminConversationsGetTeamsSchemaResponseMetadata) {
	o.ResponseMetadata = &v
}

func (o ConversationsListSuccessSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["channels"] = o.Channels
	}
	if true {
		toSerialize["ok"] = o.Ok
	}
	if !isNil(o.ResponseMetadata) {
		toSerialize["response_metadata"] = o.ResponseMetadata
	}
	return json.Marshal(toSerialize)
}

type NullableConversationsListSuccessSchema struct {
	value *ConversationsListSuccessSchema
	isSet bool
}

func (v NullableConversationsListSuccessSchema) Get() *ConversationsListSuccessSchema {
	return v.value
}

func (v *NullableConversationsListSuccessSchema) Set(val *ConversationsListSuccessSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableConversationsListSuccessSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableConversationsListSuccessSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConversationsListSuccessSchema(val *ConversationsListSuccessSchema) *NullableConversationsListSuccessSchema {
	return &NullableConversationsListSuccessSchema{value: val, isSet: true}
}

func (v NullableConversationsListSuccessSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConversationsListSuccessSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


