# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from slack.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    ADMIN_APPS = "admin.apps"
    ADMIN = "admin"
    ADMIN_APPS_APPROVED = "admin.apps.approved"
    ADMIN_APPS_REQUESTS = "admin.apps.requests"
    ADMIN_APPS_RESTRICTED = "admin.apps.restricted"
    ADMIN_CONVERSATIONS = "admin.conversations"
    ADMIN_CONVERSATIONS_EKM = "admin.conversations.ekm"
    ADMIN_CONVERSATIONS_RESTRICT_ACCESS = "admin.conversations.restrictAccess"
    ADMIN_EMOJI = "admin.emoji"
    ADMIN_INVITE_REQUESTS = "admin.inviteRequests"
    ADMIN_INVITE_REQUESTS_APPROVED = "admin.inviteRequests.approved"
    ADMIN_INVITE_REQUESTS_DENIED = "admin.inviteRequests.denied"
    ADMIN_TEAMS_ADMINS = "admin.teams.admins"
    ADMIN_TEAMS = "admin.teams"
    ADMIN_TEAMS_OWNERS = "admin.teams.owners"
    ADMIN_TEAMS_SETTINGS = "admin.teams.settings"
    ADMIN_USERGROUPS = "admin.usergroups"
    ADMIN_USERS = "admin.users"
    ADMIN_USERS_SESSION = "admin.users.session"
    API = "api"
    APPS_EVENT_AUTHORIZATIONS = "apps.event.authorizations"
    APPS = "apps"
    APPS_PERMISSIONS = "apps.permissions"
    APPS_PERMISSIONS_RESOURCES = "apps.permissions.resources"
    APPS_PERMISSIONS_SCOPES = "apps.permissions.scopes"
    APPS_PERMISSIONS_USERS = "apps.permissions.users"
    AUTH = "auth"
    BOTS = "bots"
    CALLS = "calls"
    CALLS_PARTICIPANTS = "calls.participants"
    CHAT = "chat"
    CHAT_SCHEDULED_MESSAGES = "chat.scheduledMessages"
    CONVERSATIONS = "conversations"
    DIALOG = "dialog"
    DND = "dnd"
    EMOJI = "emoji"
    FILES_COMMENTS = "files.comments"
    FILES = "files"
    FILES_REMOTE = "files.remote"
    MIGRATION = "migration"
    OAUTH = "oauth"
    OAUTH_V2 = "oauth.v2"
    PINS = "pins"
    REACTIONS = "reactions"
    REMINDERS = "reminders"
    RTM = "rtm"
    SEARCH = "search"
    STARS = "stars"
    TEAM = "team"
    TEAM_PROFILE = "team.profile"
    USERGROUPS = "usergroups"
    USERGROUPS_USERS = "usergroups.users"
    USERS = "users"
    USERS_PROFILE = "users.profile"
    VIEWS = "views"
    WORKFLOWS = "workflows"
